Repository ably/docs, pull requests merged in 2020-07, with the labels that each got.

#875 [WEB-282] fix metadata for authentication
  content/core-features/authentication.textile
  content/core-features/versions/v0.8/authentication.textile
  content/core-features/versions/v1.0/authentication.textile
Labels: ready

#910 [FEA-495] hub product code samples
  README.md
  content/code/hub-product/http-javascript.code
  content/code/hub-product/native-sdks-javascript.code
  content/code/hub-product/native-sdks-nodejs.code
  content/code/hub-product/sse-nodejs.code
  data/jsbins.yaml
Labels: review

#898 [WEB-346] Add internal links on the website to pub-sub concept
  content/concepts/mqtt.textile
  content/concepts/websub.textile
  content/core-features/pubsub.textile
  content/mqtt/index.textile
  content/tutorials/publish-subscribe.textile
Labels: api docs, ready

#902 [WEB-367] Add internal links on the website Socket.io concept
  content/concepts/feathersjs.textile
  content/concepts/websockets.textile
Labels: api docs, review

#913 tutorial writeup for p2p vue demo
  content/partials/tutorials/_setup-free-account.textile
  content/tutorials/peer-to-peer-vue.textile
Labels: tutorial content
