Repository ably/docs, pull requests merged in 2021-01, with the labels that each got.

#999 Fix: corrects case for JavaScript on selector
  lib/documentation_languages.rb
Labels: api-reference

#845 Versioning policy
  content/client-lib-development-guide/versioning.textile
  content/realtime/usage.textile
  content/realtime/versions/v0.8/usage.textile
  content/realtime/versions/v1.0/usage.textile
  content/rest-api/index.textile
  content/rest/usage.textile
  content/rest/versions/v0.8/usage.textile
  content/rest/versions/v1.0/usage.textile
  content/tutorials/reactor-event-google.textile
  content/tutorials/webhook-chuck-norris.textile
Labels: client-lib-spec

#1009 [WEB-1297] update logo
  app/assets/favicon.ico
  app/assets/favicon.svg
  app/assets/images/ably-logo-white-outline.png
  app/assets/images/ably-logo.png
  data/redirects.yaml
  layouts/_head.html.erb
Labels: content-request, in-progress
