Repository ably/docs, pull requests merged in 2022-08, with the labels that each got.

#1500 [EDX-127] Sync global and local programming language selector
  data/createPages/createContentMenuDataFromPage.js
  package-lock.json
  package.json
  src/components/Button/LanguageButton.tsx
  src/components/Link/LanguageLink.tsx
  src/components/Menu/LanguageNavigation.tsx
  src/components/Menu/TopCodeMenu.tsx
  src/components/Menu/styles.css
  src/components/Sidebar/SidebarLinkMenu.js
  src/components/blocks/Html/DangerousHtml.tsx
  src/components/blocks/software/Pre.tsx
  src/components/blocks/software/__snapshots__/Pre.test.js.snap
  src/components/blocks/software/pre-props.ts
  src/components/blocks/wrappers/ConditionalChildrenLanguageDisplay.js
  src/components/blocks/wrappers/ConditionalLanguageDisplay.js
  src/components/blocks/wrappers/LocalLanguageAlternatives.js
  src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
  src/components/blocks/wrappers/README.md
  src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.js.snap
  src/components/blocks/wrappers/language-utilities.js
  src/components/blocks/wrappers/language-utilities.test.ts
  src/components/blocks/wrappers/language-utilities.ts
  src/components/common/language-defaults.test.ts
  src/components/common/language-defaults.ts
  src/contexts/page-language-context.ts
  src/templates/document.js
  src/utilities/browser/safe-window.ts
  src/utilities/language/constants.ts
Labels: new-toolchain

#1515 [EDX-59] Specify langs with frontmatter
  data/createPages/constants.ts
  data/transform/front-matter.js
  data/transform/front-matter.ts
  graphql-types.ts
  src/templates/document.js
Labels: new-toolchain

#1516 Add params argument to PushChannel#listSubscriptions
  content/client-lib-development-guide/features.textile
Labels: client-lib-spec

#1517 Update RealtimePresence.subscribe to support an array of actions
  content/client-lib-development-guide/features.textile
Labels: client-lib-spec

#1521 [EDX-128] New design - Version & Language selectors
  graphql-types.ts
  src/clientside-data-utilities/clientside-data-utilities.test.ts
  src/components/Header/Header.tsx
  src/components/Layout/Layout.tsx
  src/components/Menu/Label/index.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/CSharp.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/DotNet.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/Flutter.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/Go.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/Java.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/JavaScript.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/NodeJs.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/ObjC.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/Php.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/Python.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/Ruby.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageLogos/Swift.tsx
  src/components/Menu/LanguageDropdownSelector/README.md
  src/components/Menu/LanguageDropdownSelector/image-map.ts
  src/components/Menu/ReactSelectCustomComponents/Formatters/FormatOptionLabelWithLanguageLogo.tsx
  src/components/Menu/ReactSelectCustomComponents/no-indicator-separator.ts
  src/components/Menu/ReactSelectStyles/Versions/no-padding-value-container-styles.ts
  src/components/Menu/ReactSelectStyles/control-styles.ts
  src/components/Menu/ReactSelectStyles/custom-react-select-styles.ts
  src/components/Menu/ReactSelectStyles/dropdown-indicator-styles.ts
  src/components/Menu/ReactSelectStyles/group-heading-styles.ts
  src/components/Menu/ReactSelectStyles/menu-list-styles.ts
  src/components/Menu/ReactSelectStyles/option-styles.ts
  src/components/Menu/TopCodeMenu.tsx
  src/components/Menu/VersionMenu.js
  src/components/Menu/VersionMenu.tsx
  src/components/Menu/index.js
  src/components/Menu/index.tsx
  src/components/Menu/react-select-option-types.ts
  src/components/Menu/route-to-page.ts
  src/components/Menu/styles.css
  src/components/Notifications/Warning.tsx
  src/components/blocks/software/__snapshots__/Pre.test.js.snap
  src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.js.snap
  src/components/common/language-defaults.ts
  src/templates/document.js
Labels: new-toolchain

#1514 [EDX-129] New design for site top nav
  .eslintrc.json
  package.json
  src/components/Header/Header.tsx
  src/components/Header/TopMainNav/Dropdown/Button/AccountPanel/AccountOptions.tsx
  src/components/Header/TopMainNav/Dropdown/Button/AccountPanel/AccountPanel.tsx
  src/components/Header/TopMainNav/Dropdown/Button/AccountPanel/AccountUtilityLinks.tsx
  src/components/Header/TopMainNav/Dropdown/Button/AccountPanel/index.ts
  src/components/Header/TopMainNav/Dropdown/Button/AccountPanelDropdownData.tsx
  src/components/Header/TopMainNav/Dropdown/Button/DropdownButton.tsx
  src/components/Header/TopMainNav/Dropdown/Button/api-references.ts
  src/components/Header/TopMainNav/Dropdown/Button/dropdown-data.ts
  src/components/Header/TopMainNav/Dropdown/Button/index.ts
  src/components/Header/TopMainNav/Dropdown/Button/resource-data.ts
  src/components/Header/TopMainNav/Dropdown/Contents/ContentDescription.tsx
  src/components/Header/TopMainNav/Dropdown/Contents/ContentLink.tsx
  src/components/Header/TopMainNav/Dropdown/Contents/ContentsContainer.tsx
  src/components/Header/TopMainNav/Dropdown/Contents/DropdownItemContent.tsx
  src/components/Header/TopMainNav/Dropdown/Contents/Title.tsx
  src/components/Header/TopMainNav/Dropdown/Contents/index.ts
  src/components/Header/TopMainNav/Dropdown/Contents/types.ts
  src/components/Header/TopMainNav/Dropdown/DropdownMenu.tsx
  src/components/Header/TopMainNav/Dropdown/DropdownMenuContainer.tsx
  src/components/Header/TopMainNav/Dropdown/Summary/Summary.tsx
  src/components/Header/TopMainNav/Dropdown/Summary/SummaryLinkIcon.tsx
  src/components/Header/TopMainNav/Dropdown/Summary/index.ts
  src/components/Header/TopMainNav/Dropdown/index.ts
  src/components/Header/TopMainNav/Dropdown/types.ts
  src/components/Header/TopMainNav/SearchBar/SearchBar.tsx
  src/components/Header/TopMainNav/SearchBar/SearchIcon.tsx
  src/components/Header/TopMainNav/SearchBar/index.ts
  src/components/Header/TopMainNav/TopMainNav.tsx
  src/components/Header/TopMainNav/TopMainNavIllustration/TopMainNavAblyLogo.tsx
  src/components/Header/TopMainNav/TopMainNavUser/MaybeSignedIn.tsx
  src/components/Header/TopMainNav/TopMainNavUser/SignedIn/SignIn.tsx
  src/components/Header/TopMainNav/TopMainNavUser/SignedIn/SignOutLink.tsx
  src/components/Header/TopMainNav/TopMainNavUser/SignedIn/SignedInPlaceholder.tsx
  src/components/Header/TopMainNav/TopMainNavUser/SignedIn/index.ts
  src/components/Header/TopMainNav/TopMainNavUser/SignedOut.tsx
  src/components/Header/TopMainNav/TopMainNavUser/TopMainNavLink.tsx
  src/components/Header/TopMainNav/TopMainNavUser/TopMainNavUserMenu.tsx
  src/components/Header/TopMainNav/TopMainNavUser/index.ts
  src/components/Header/TopMainNav/index.ts
  src/components/Menu/HorizontalMenuItemGroup.tsx
  src/components/Menu/TopCodeMenu.tsx
  src/components/Menu/VersionMenu.tsx
  src/components/Sidebar/ExpandableIndicator.tsx
  src/components/Sidebar/SidebarItem.js
  src/contexts/user-context.ts
  static/images/icons/search-icon.svg
  tailwind.config.js
Labels: new-toolchain

#1502 [EDU-765] Update jwt authentication tutorial
  app/assets/images/tutorials/jwt-auth/jwt-auth-output.png
  app/assets/stylesheets/live-demo.scss
  app/assets/stylesheets/stylesheet.scss
  content/tutorials/jwt-authentication.textile
Labels: Do not merge

#1519 [EDU-910] - Update free tier limits
  content/general/limits.textile
Labels: in-progress

#1545 EDX-231: Create sitemaps for docs
  .eslintrc.json
  gatsby-config.ts
  package.json
Labels: new-toolchain

#1549 [EDX-21] Avoid building the site if we are missing meta descriptions
  data/createPages/index.js
  data/onCreateNode/index.js
  data/transform/index.js
  gatsby-node.ts
  graphql-types.ts
Labels: new-toolchain

#1527 [EDX-11] Create Docs Homepage
  content/index.textile
  data/yaml/page-content/homepage.yaml
  gatsby-config.ts
  graphql-types.ts
  package-lock.json
  package.json
  src/components/Article/index.tsx
  src/components/Homepage/BodySection/BodySection.tsx
  src/components/Homepage/BodySection/BodySectionDescription.tsx
  src/components/Homepage/BodySection/BodySectionDescriptionContainer.tsx
  src/components/Homepage/BodySection/Card/Card.tsx
  src/components/Homepage/BodySection/Card/CardContent.tsx
  src/components/Homepage/BodySection/Card/CardFlag.tsx
  src/components/Homepage/BodySection/Card/CardHeader.tsx
  src/components/Homepage/BodySection/Card/CardLink.tsx
  src/components/Homepage/BodySection/Card/CardTitle.tsx
  src/components/Homepage/HomepageContent.tsx
  src/components/Layout/Layout.tsx
  src/components/Sidebar/ExpandableIndicator.tsx
  src/pages/docs.tsx
  src/pages/documentation.js
  src/pages/index.js
  src/pages/index.tsx
  src/styles/svg/ai-chevron-down.tsx
  src/styles/svg/ai-chevron-up.tsx
  src/styles/svg/ai-link.tsx
  src/styles/svg/notification-levels/ai-barricade.tsx
  src/templates/document.js
  static/images/icons/arrow-right.svg
  tailwind.config.js
Labels: new-toolchain

#1561 [EDX-134] Redirect Functionality
  README.md
  data/createPages/index.js
  data/transform/front-matter.ts
  data/transform/index.js
  gatsby-config.ts
  gatsby-node.ts
  graphql-types.ts
  package-lock.json
  package.json
  src/templates/document.js
Labels: new-toolchain

#1551 EDX-136: Integrate add search for search functionality no UI/UX
  .env.example
  .eslintrc.json
  gatsby-config.ts
  graphql-types.ts
  jest.config.js
  package-lock.json
  package.json
  setupTests.js
  src/components/Header/TopMainNav/SearchBar/SearchBar.tsx
  src/hooks/index.ts
  src/hooks/use-search/index.ts
  src/hooks/use-search/use-search.test.tsx
  src/hooks/use-search/use-search.ts
  tsconfig.json
Labels: new-toolchain

#1531 [EDX-241] - Styling fixes, refactor
  .eslintrc.json
  data/yaml/page-furniture/sidebar.yaml
  graphql-types.ts
  package-lock.json
  package.json
  src/components/Header/TopMainNav/Dropdown/Button/AccountPanel/AccountPanel.tsx
  src/components/Header/TopMainNav/Dropdown/Button/DropdownButton.test.tsx
  src/components/Header/TopMainNav/Dropdown/Button/DropdownButton.tsx
  src/components/Header/TopMainNav/Dropdown/Button/index.ts
  src/components/Header/TopMainNav/Dropdown/Button/resource-data.ts
  src/components/Header/TopMainNav/Dropdown/Contents/ContentLink.tsx
  src/components/Header/TopMainNav/Dropdown/Contents/ContentsContainer.tsx
  src/components/Header/TopMainNav/Dropdown/Contents/DropdownItemContent.tsx
  src/components/Header/TopMainNav/Dropdown/Contents/ExternalLinkIndicator.tsx
  src/components/Header/TopMainNav/Dropdown/Contents/types.ts
  src/components/Header/TopMainNav/Dropdown/DropdownMenu.tsx
  src/components/Header/TopMainNav/Dropdown/DropdownMenuContainer.tsx
  src/components/Header/TopMainNav/Dropdown/Summary/Summary.tsx
  src/components/Header/TopMainNav/Dropdown/types.ts
  src/components/Header/TopMainNav/SearchBar/SearchBar.tsx
  src/components/Header/TopMainNav/TopMainNav.tsx
  src/components/Header/TopMainNav/TopMainNavIllustration/TopMainNavAblyLogo.tsx
  src/components/Header/TopMainNav/TopMainNavUser/MaybeSignedIn.tsx
  src/components/Header/TopMainNav/TopMainNavUser/SignedIn/SignIn.tsx
  src/components/Header/TopMainNav/TopMainNavUser/SignedOut.tsx
  src/components/Header/TopMainNav/TopMainNavUser/TopMainNavLink.tsx
  src/components/Header/TopMainNav/TopMainNavUser/TopMainNavUserMenu.tsx
  src/components/Header/TopMainNav/main-nav-reducer.test.ts
  src/components/Header/TopMainNav/main-nav-reducer.ts
  src/components/Header/TopMainNav/top-main-nav-state-context.ts
  src/components/Menu/HorizontalMenuItemGroup.tsx
  src/components/Menu/styles.css
  src/hooks/useFunctionOnOutsideClick.ts
  static/images/icons/external-link.svg
  tailwind.config.js
Labels: new-toolchain
