Repository ably/docs, pull requests merged in 2022-09, with the labels that each got.

#1564 [EDX-202] Render unwrapped root level text in p elements
  .githooks/README.md
  .githooks/post-checkout
  .githooks/pre-commit
  README.md
  data/transform/post-parser/README.md
  data/transform/post-parser/index.js
  data/transform/post-parser/root-level-text-wrapper.test.ts
  data/transform/post-parser/root-level-text-wrapper.ts
  graphql-types.ts
  package-lock.json
  package.json
Labels: new-toolchain

#1559 [EDX-125] Update code snippet design and functionality
  __mocks__/gatsby.js
  babel.config.js
  graphql-types.ts
  jest.config.js
  package-lock.json
  package.json
  src/components/ButtonWithTooltip/ButtonWithTooltip.module.css
  src/components/ButtonWithTooltip/ButtonWithTooltip.test.tsx
  src/components/ButtonWithTooltip/ButtonWithTooltip.tsx
  src/components/ButtonWithTooltip/index.ts
  src/components/Header/TopMainNav/Dropdown/Button/DropdownButton.test.tsx
  src/components/Header/TopMainNav/TopMainNav.tsx
  src/components/HorizontalMenu/HorizontalMenu.module.css
  src/components/HorizontalMenu/HorizontalMenu.test.tsx
  src/components/HorizontalMenu/HorizontalMenu.tsx
  src/components/HorizontalMenu/index.ts
  src/components/LanguageButton/LanguageButton.module.css
  src/components/LanguageButton/LanguageButton.test.tsx
  src/components/LanguageButton/LanguageButton.tsx
  src/components/LanguageButton/index.ts
  src/components/Link/LanguageLink.tsx
  src/components/Menu/Label/index.tsx
  src/components/Menu/LanguageNavigation.tsx
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItem/MenuItemButton/index.tsx
  src/components/Menu/MenuItem/index.js
  src/components/Menu/MenuItem/index.ts
  src/components/Menu/MenuItemButton/MenuItemButton.module.css
  src/components/Menu/MenuItemButton/MenuItemButton.test.tsx
  src/components/Menu/MenuItemButton/MenuItemButton.tsx
  src/components/Menu/MenuItemButton/index.tsx
  src/components/Menu/TopCodeMenu.tsx
  src/components/Menu/index.tsx
  src/components/Menu/styles.css
  src/components/blocks/Html/index.tsx
  src/components/blocks/software/Code.test.js
  src/components/blocks/software/Code/ApiKeyMenuSelector.tsx
  src/components/blocks/software/Code/Code.test.tsx
  src/components/blocks/software/Code/CodeCopyButton.test.tsx
  src/components/blocks/software/Code/CodeCopyButton.tsx
  src/components/blocks/software/Code/MultilineCodeContent.tsx
  src/components/blocks/software/Code/__snapshots__/Code.test.tsx.snap
  src/components/blocks/software/Code/index.js
  src/components/blocks/software/Code/index.tsx
  src/components/blocks/software/Code/prismjs-overwrite.css
  src/components/blocks/software/Pre.tsx
  src/components/blocks/software/__snapshots__/Code.test.js.snap
  src/components/blocks/software/__snapshots__/Pre.test.js.snap
  src/components/blocks/software/pre-props.ts
  src/components/blocks/software/styles.css
  src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
  src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.js.snap
  src/components/common/language-defaults.test.ts
  src/components/common/language-defaults.ts
  src/components/index.ts
  src/hooks/use-search/use-search.test.ts
  src/maps/language.tsx
  src/types/non-javascript-assets/css.d.ts
  tailwind.config.js
Labels: new-toolchain

#1537 [EDU-827] - Update JS/Node version of Presence tutorial
  content/tutorials/presence.textile
Labels: tutorials

#1569 [EDX-135] Update UI for API references
  data/createPages/createPageVariants.js
  data/createPages/index.js
  data/onCreateNode/create-graphql-schema-customization.ts
  data/transform/constants.js
  data/transform/constants.ts
  data/transform/index.js
  gatsby-node.ts
  graphql-types.ts
  src/components/ButtonWithTooltip/ButtonWithTooltip.module.css
  src/components/Head.tsx
  src/components/LanguageButton/LanguageButton.module.css
  src/components/LanguageButton/LanguageButton.test.tsx
  src/components/LanguageButton/LanguageButton.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
  src/components/Menu/MenuItemButton/MenuItemButton.test.tsx
  src/components/PageTitle.tsx
  src/components/blocks/Html/index.tsx
  src/components/blocks/api-reference/external-references/ApiReferenceBlockquote.tsx
  src/components/blocks/api-reference/headings/ApiReferenceH6.tsx
  src/components/blocks/api-reference/software/Code/ApiReferenceCode.tsx
  src/components/blocks/api-reference/software/Code/ApiReferenceInlineCodeElement.tsx
  src/components/blocks/block-component-maps/component-map.js
  src/components/blocks/block-component-maps/component-map.test.js
  src/components/blocks/block-component-maps/index.ts
  src/components/blocks/create-blocks/api-reference-blocks-from-data.js
  src/components/blocks/create-blocks/default-blocks-from-data.js
  src/components/blocks/external-references/A.tsx
  src/components/blocks/software/Code/index.tsx
  src/components/blocks/software/Pre.tsx
  src/components/blocks/software/__snapshots__/Pre.test.js.snap
  src/components/blocks/typography/P/Tip.tsx
  src/components/blocks/typography/P/index.tsx
  src/components/blocks/wrappers/ConditionalChildrenLanguageDisplay.test.js
  src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
  src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
  src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.js.snap
  src/components/html-component-props.ts
  src/contexts/article-type-context.ts
  src/templates/apiReference.tsx
  src/templates/base-template.tsx
  src/templates/document.tsx
  src/templates/template-data.d.ts
  src/utilities/browser/storage.ts
  tailwind.config.js
Labels: new-toolchain

#1575 [EDX-262] "Need Help?" section
  graphql-types.ts
  package.json
  src/components/Article/ArticleFooter.tsx
  src/components/Article/InArticleBanner/InArticleBanner.tsx
  src/components/Article/InArticleBanner/InArticleBannerCopy.tsx
  src/components/Article/InArticleBanner/InArticleOptions.tsx
  src/components/Article/InArticleBanner/index.ts
  src/components/Article/index.tsx
Labels: new-toolchain

#1577 [Fix] - Style tweaks
  README.md
  package-lock.json
  src/components/Header/TopMainNav/Dropdown/Button/DropdownButton.tsx
  src/components/Sidebar/styles.js
Labels: new-toolchain

#1574 [EDX-125]: Update code snippet design and functionality (api dropdown)
  package-lock.json
  package.json
  src/components/HorizontalMenu/HorizontalMenu.tsx
  src/components/LanguageButton/LanguageButton.module.css
  src/components/LanguageButton/LanguageButton.tsx
  src/components/Menu/Label/Label.module.css
  src/components/Menu/Label/index.tsx
  src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
  src/components/Menu/LanguageDropdownSelector/README.md
  src/components/Menu/LanguageNavigation.tsx
  src/components/Menu/LanguageNavigation/LanguageNavigation.module.css
  src/components/Menu/LanguageNavigation/LanguageNavigation.tsx
  src/components/Menu/LanguageNavigation/index.ts
  src/components/Menu/ReactSelectCustomComponents/Formatters/FormatOptionLabelWithLanguageLogo.tsx
  src/components/Menu/ReactSelectStyles/Versions/no-padding-value-container-styles.ts
  src/components/Menu/ReactSelectStyles/control-styles.ts
  src/components/Menu/ReactSelectStyles/dropdown-indicator-styles.ts
  src/components/Menu/ReactSelectStyles/group-heading-styles.ts
  src/components/Menu/ReactSelectStyles/menu-list-styles.ts
  src/components/Menu/ReactSelectStyles/menu-styles.ts
  src/components/Menu/ReactSelectStyles/option-styles.ts
  src/components/Menu/ReactSelectStyles/single-value-styles.ts
  src/components/Menu/VersionMenu.tsx
  src/components/Menu/route-to-page.ts
  src/components/Select/Select.tsx
  src/components/Select/index.ts
  src/components/Select/styles.ts
  src/components/Select/types.ts
  src/components/blocks/software/Code/ApiKeyMenu.module.css
  src/components/blocks/software/Code/ApiKeyMenu.tsx
  src/components/blocks/software/Code/ApiKeyMenuSelector.tsx
  src/components/blocks/software/Code/MultilineCodeContent.tsx
  src/components/blocks/software/Code/api-key-menu-styles.ts
  src/components/blocks/software/Code/index.tsx
  src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/contexts/index.ts
  src/hooks/get-current-header-id.ts
  src/utilities/index.ts
  src/utilities/language/cache-visit-preferred-language.ts
Labels: new-toolchain

#1578 [EDX-139] No code snippet exists for lang selected - design/ implementation update
  src/components/LanguageButton/LanguageButton.module.css
  src/components/blocks/software/Pre.test.js
  src/components/blocks/software/Pre.test.tsx
  src/components/blocks/software/Pre.tsx
  src/components/blocks/software/__snapshots__/Pre.test.js.snap
  src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
  src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
Labels: new-toolchain

#1579 EDU-857: Fix broken links in docs
  content/client-lib-development-guide/comet.textile
  content/client-lib-development-guide/versions/v1.1/features.textile
  content/client-lib-development-guide/websocket.textile
  content/protocol-adapters/index.textile
Labels: bug

#1589 [EDX-272] Global language selector default label
  data/createPages/constants.ts
  src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
Labels: new-toolchain

#1160 Make RTL5K also apply to detached state
  content/client-lib-development-guide/features.textile
Labels: client-lib-spec

#1530 Clarification that the text in TP4 is not just a copy-paste of TM3
  content/client-lib-development-guide/features.textile
Labels: client-lib-spec

#1590 Chore: add typescript components
  package-lock.json
  package.json
  src/components/blocks/Html/GenericHtmlBlock.js
  src/components/blocks/complex-functionality/Button.tsx
  src/components/blocks/complex-functionality/Meter.tsx
  src/components/blocks/complex-functionality/Noscript.tsx
  src/components/blocks/complex-functionality/Progress.tsx
  src/components/blocks/complex-functionality/Select.tsx
  src/components/blocks/complex-functionality/Textarea.tsx
  src/components/blocks/dividers/Article.tsx
  src/components/blocks/dividers/Aside.tsx
  src/components/blocks/dividers/Div.tsx
  src/components/blocks/dividers/Main.tsx
  src/components/blocks/dividers/Section.tsx
  src/components/blocks/dividers/Span.tsx
  src/components/blocks/dividers/index.ts
  src/components/blocks/external-references/A.test.tsx
  src/components/blocks/external-references/Address.tsx
  src/components/blocks/external-references/Audio.tsx
  src/components/blocks/external-references/Blockquote.tsx
  src/components/blocks/external-references/Iframe.tsx
  src/components/blocks/external-references/Quote.tsx
  src/components/blocks/external-references/Video.tsx
  src/components/blocks/external-references/__snapshots__/A.test.tsx.snap
  src/components/blocks/external-references/index.ts
  src/components/blocks/headings/H1.tsx
  src/components/blocks/headings/H2.tsx
  src/components/blocks/headings/H3.tsx
  src/components/blocks/headings/H4.tsx
  src/components/blocks/headings/H5.tsx
  src/components/blocks/headings/H6.tsx
  src/components/blocks/headings/Header.tsx
  src/components/blocks/headings/index.ts
  src/components/blocks/list/Dd.tsx
  src/components/blocks/list/Dl/DefinitionListRow.tsx
  src/components/blocks/list/Dl/index.tsx
  src/components/blocks/list/Dt.tsx
  src/components/blocks/list/Li.tsx
  src/components/blocks/list/Ol.tsx
  src/components/blocks/list/Ul.tsx
  src/components/blocks/list/index.ts
  src/components/blocks/list/reset-styles.ts
  src/components/blocks/non-semantic/Br.tsx
  src/components/blocks/non-semantic/Wbr.tsx
  src/components/blocks/semantic-enhancements/Abbr.tsx
  src/components/blocks/semantic-enhancements/Details.tsx
  src/components/blocks/semantic-enhancements/Dfn.tsx
  src/components/blocks/semantic-enhancements/Summary.tsx
  src/components/blocks/semantic-enhancements/Time.tsx
  src/components/blocks/semantic-enhancements/index.ts
  src/components/blocks/software/Kbd.tsx
  src/components/blocks/software/Output.tsx
  src/components/blocks/software/Samp.tsx
  src/components/blocks/software/Var.tsx
  src/components/blocks/typography/P/PendingClassName.js
  src/components/blocks/typography/P/PendingClassName.tsx
  src/components/blocks/typography/index.ts
  src/components/html-component-props.ts
Labels: new-toolchain

#1600 [EDX-235] Tutorial page needs to be removed from the docs site
  data/transform/index.js
Labels: new-toolchain

#1605 [EDX-300] Preferred language not set correctly
  src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
  src/templates/base-template.tsx
Labels: new-toolchain

#1602 [EDX-294] API Reference language display
  content/api/realtime-sdk/channels.textile
  data/html-parser/index.ts
  data/html-parser/remove-children-from-pre-wrapped-code-elements.test.ts
  data/html-parser/remove-children-from-pre-wrapped-code-elements.ts
  data/transform/post-parser/blang.ts
  data/transform/post-parser/constants.ts
  data/transform/post-parser/index.js
  data/transform/post-parser/index.ts
  data/transform/post-parser/root-level-text-wrapper.test.ts
  data/transform/post-parser/root-level-text-wrapper.ts
  data/transform/pre-parser/index.ts
  data/transform/string-transformation.d.ts
  src/clientside-data-utilities/index.ts
  src/components/blocks/Html/LinkableHtmlBlock.js
  src/components/blocks/api-reference/dividers/ApiReferenceDiv.tsx
  src/components/blocks/api-reference/dividers/ApiReferenceSpan.tsx
  src/components/blocks/api-reference/headings/ApiReferenceH6.tsx
  src/components/blocks/api-reference/list/ApiReferenceDd.tsx
  src/components/blocks/api-reference/list/ApiReferenceDt.tsx
  src/components/blocks/api-reference/software/Code/ApiReferenceCode.tsx
  src/components/blocks/block-component-maps/component-map.js
  src/components/blocks/headings/H4.tsx
  src/components/blocks/software/Code/index.tsx
  src/components/blocks/software/Pre.tsx
  src/components/blocks/wrappers/ConditionalChildrenLanguageDisplay.js
  src/components/blocks/wrappers/CopyLink.tsx
  src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
  src/components/blocks/wrappers/language-utilities.test.ts
  src/components/blocks/wrappers/language-utilities.ts
  src/components/html-component-props.ts
  src/hooks/use-search/use-search.test.ts
  src/react-utilities/index.js
  src/templates/apiReference.tsx
Labels: new-toolchain

#1604 [EDX-260] Tables UI/ UX
  src/components/blocks/table/Caption.ts
  src/components/blocks/table/Col.ts
  src/components/blocks/table/Colgroup.ts
  src/components/blocks/table/Table.js
  src/components/blocks/table/Table.module.css
  src/components/blocks/table/Table.tsx
  src/components/blocks/table/Tbody.js
  src/components/blocks/table/Tbody.tsx
  src/components/blocks/table/Td.js
  src/components/blocks/table/Td.tsx
  src/components/blocks/table/Tfoot.ts
  src/components/blocks/table/Th.js
  src/components/blocks/table/Th.module.css
  src/components/blocks/table/Th.tsx
  src/components/blocks/table/Thead.ts
  src/components/blocks/table/Tr.js
  src/components/blocks/table/Tr.tsx
  src/components/blocks/table/index.ts
Labels: new-toolchain

#1606 [EDX-266] Update UI/ UX of the old version warning message
  src/components/Menu/VersionMenu.tsx
  src/components/Notification/Notification.test.tsx
  src/components/Notification/Notification.tsx
  src/components/Notification/index.ts
  src/components/Notifications/Notice.js
  src/components/Notifications/Warning.tsx
  src/components/Notifications/index.js
  src/styles/svg/ai-close-rounded.tsx
  src/styles/svg/notification-levels/ai-barricade.tsx
Labels: new-toolchain
